### ISSUE TITLE
Investigate Performance

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/afm-controller#60]
We should find some WIndows tools to characterize the performance of the program when:
- [ ] running but not doing anything
- [ ] running the analysis VI
- [ ] running and enforcing set-points
- [ ] running and executing experiments
- [ ] running and not doing anything, after soaking for hours or days
#55 should improve performance when "not doing anything" by removing polling but if we don't close references correctly, etc, we could have terrible performance when soaking.
