### ISSUE TITLE
Build Documentation

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/afm-controller#67]
We sorely need documentation:
- [ ] nice intro to the project in README
- [ ] how to get started guide in README
- [ ] how to contribute guide in README
- [ ] architecture overview in wiki
- [ ] experiment API in wiki
- [ ] extended help for GUI/features/etc in wiki
- [ ] example of a workflow? in wiki
